baseurl: http://blacksmith.community/
blackfriday:
  fractions: true
  plainIDAnchors: true
  smartDashes: true
  smartypants: true
canonifyurls: true
googleAnalytics: ""
languageCode: en-us
menu:
  main:
  - name: Blacksmith
    url: /
    weight: 0
  - name: Deploying
    url: deploying/
    weight: 10
  - name: Getting started
    url: getting-started/
    weight: 20
metadataformat: yaml
params:
  author: Long Nguyen
  copyright: Released under the MIT license
  custom_css: []
  custom_js: []
  description: Building production services for Cloud Foundry
  favicon: ""
  font:
    code: Ubuntu Mono
    text: Ubuntu
  highlight_css: ""
  logo: images/logo.png
  palette:
    accent: light green
    primary: red
  permalink: '#'
  provider: GitHub
  repo_url: https://github.com/cloudfoundry-community/blacksmith
  version: 0.1.0
social:
  github: blacksmith-community
  twitter: blacksmith-community
theme: hugo-material-docs
title: Blacksmith
